---
title: "Homework 5"
author: "Shritama Ray"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document

---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(broom)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### Problem 1

Tidy longitudinal data

### Problem 2

### Problem 3: Power in a 1-sample t-test

n = 30
sigma = 5
mu = 0

Generate 5000 datasets from the model: x ~ Normal[mu, sigma]:
```{r sim mean sd}

#create function
sim_mean_pval = function(n, mu = 0, sigma = 5) {
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      p_val = t.test(x, mu = mu, alternative = "less", conf.level = 0.95) %>%
        broom::tidy() %>%
        select(p.value)
    )
}

#run function 5000 times and save results to a list
output = vector("list", 100)

for (i in 1:100) {
  output[[i]] = sim_mean_pval(30)
}

sim_results = bind_rows(output)
  
```


